---
# tasks file for apache_install
 - name: Install Apache WebServer
   yum:
      name=httpd
      state=latest

 - name: Start Apache and Enable it on the every boot
   service:
     name=httpd
     state=started
     enabled=yes

 - name: permit traffic in default zone on port 80/tcp
   ansible.posix.firewalld:
     port: 80/tcp
     permanent: yes
     state: enabled

 - name: firewall reload
   service:
     name: firewalld
     state: restarted

 - name: Copy to the index.html
   copy:
      content: "{{ ansible_facts.all_ipv4_addresses, ansible_facts.hostname, ansible_facts.memfree_mb, ansible_facts.processor_cores  }} \n"
      dest: "/var/www/html/index.html"

 - name: Check that you can connect (GET) to a page and it returns a status 200
   uri:
     url: http://localhost
     method: GET
     return_content: yes
     status_code: 200
     body_format: json
   register: variable

 - name: Show Value of Variable
   debug:
      msg: "{{ variable }}"
