version: "3"
services:
  netology-db:
    image: postgres:13        # Образ, который мы будем использовать
    container_name: buravtsovps-netology-db   # Имя, которым будет называться наш контейнер	
    ports:  # Порты, которые мы пробрасываем с нашего докер сервера внутрь контейнера
      - 5432:5432
    volumes: # Папка, которую мы пробросим с докер сервера внутрь контейнера
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:  # Переменные среды
      POSTGRES_PASSWORD: buravtsovps12!3!! # Задаём пароль от пользователя postgres
      POSTGRES_DB: buravtsovps # БД которая сразу же будет создана
      PGDATA: /var/lib/postgresql/data/pgdata # Путь внутри контейнера, где будет папка 
    networks:
     buravtsovps-my-netology-hw:
        ipv4_address: 172.22.0.2
    restart: always # Режим перезапуска контейнера. Контейнер всегда будет перезапускаться
 
  pgadmin:
    image: dpage/pgadmin4
    container_name: buravtsovps-pgadmin
    environment:
     PGADMIN_DEFAULT_EMAIL: buravtsov@gmail.com
     PGADMIN_DEFAULT_PASSWORD: 123
    ports:
       - 61231:80
    networks:
     buravtsovps-my-netology-hw:
       ipv4_address: 172.22.0.3
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
      - netology-db
    container_name: buravtsovps-zabbix-netology
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: buravtsovps12!3!!
    ports:
      - "10051:10051"
    networks:
      buravtsovps-my-netology-hw:
        ipv4_address: 172.22.0.4
    restart: always

  zabbix_wgui:
    image: zabbix/zabbix-web-apache-pgsql
    links:
      - netology-db
      - zabbix-server
    container_name: buravtsovps-netology_zabbix_frontend
    environment:
       DB_SERVER_HOST: '172.22.0.2'
       POSTGRES_USER: 'postgres'
       POSTGRES_PASSWORD: buravtsovps12!3!!
       ZBX_SERVER_HOST: "zabbix-server"
       PHP_TZ: "asia/yekaterinburg"
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      buravtsovps-my-netology-hw:
         ipv4_address: 172.22.0.5
    restart: always


networks:
 buravtsovps-my-netology-hw:
   driver: bridge
   ipam:
     config:
     - subnet: 172.22.0.0/24
